# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\logbookguimainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(870, 631)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 861, 581))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.logbook = QtGui.QWidget()
        self.logbook.setObjectName(_fromUtf8("logbook"))
        self.tableLogbook = QtGui.QTableWidget(self.logbook)
        self.tableLogbook.setGeometry(QtCore.QRect(20, 20, 811, 491))
        self.tableLogbook.setObjectName(_fromUtf8("tableLogbook"))
        self.tableLogbook.setColumnCount(9)
        self.tableLogbook.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableLogbook.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableLogbook.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableLogbook.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableLogbook.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableLogbook.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableLogbook.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableLogbook.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableLogbook.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableLogbook.setHorizontalHeaderItem(8, item)
        self.buttonLogbook = QtGui.QPushButton(self.logbook)
        self.buttonLogbook.setGeometry(QtCore.QRect(750, 520, 81, 23))
        self.buttonLogbook.setObjectName(_fromUtf8("buttonLogbook"))
        self.tabWidget.addTab(self.logbook, _fromUtf8(""))
        self.users = QtGui.QWidget()
        self.users.setObjectName(_fromUtf8("users"))
        self.tableUsers = QtGui.QTableWidget(self.users)
        self.tableUsers.setGeometry(QtCore.QRect(20, 20, 811, 491))
        self.tableUsers.setObjectName(_fromUtf8("tableUsers"))
        self.tableUsers.setColumnCount(3)
        self.tableUsers.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableUsers.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableUsers.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableUsers.setHorizontalHeaderItem(2, item)
        self.buttonUser = QtGui.QPushButton(self.users)
        self.buttonUser.setGeometry(QtCore.QRect(750, 520, 81, 23))
        self.buttonUser.setObjectName(_fromUtf8("buttonUser"))
        self.tabWidget.addTab(self.users, _fromUtf8(""))
        self.setups = QtGui.QWidget()
        self.setups.setObjectName(_fromUtf8("setups"))
        self.tableSetups = QtGui.QTableWidget(self.setups)
        self.tableSetups.setGeometry(QtCore.QRect(20, 20, 811, 491))
        self.tableSetups.setObjectName(_fromUtf8("tableSetups"))
        self.tableSetups.setColumnCount(5)
        self.tableSetups.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableSetups.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableSetups.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableSetups.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableSetups.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableSetups.setHorizontalHeaderItem(4, item)
        self.buttonSetup = QtGui.QPushButton(self.setups)
        self.buttonSetup.setGeometry(QtCore.QRect(750, 520, 81, 23))
        self.buttonSetup.setObjectName(_fromUtf8("buttonSetup"))
        self.tabWidget.addTab(self.setups, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 870, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_Open = QtGui.QAction(MainWindow)
        self.action_Open.setObjectName(_fromUtf8("action_Open"))
        self.action_Quit = QtGui.QAction(MainWindow)
        self.action_Quit.setObjectName(_fromUtf8("action_Quit"))
        self.action_New = QtGui.QAction(MainWindow)
        self.action_New.setObjectName(_fromUtf8("action_New"))
        self.menuFile.addAction(self.action_Open)
        self.menuFile.addAction(self.action_New)
        self.menuFile.addAction(self.action_Quit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.tableLogbook)
        MainWindow.setTabOrder(self.tableLogbook, self.buttonLogbook)
        MainWindow.setTabOrder(self.buttonLogbook, self.tableUsers)
        MainWindow.setTabOrder(self.tableUsers, self.buttonUser)
        MainWindow.setTabOrder(self.buttonUser, self.tableSetups)
        MainWindow.setTabOrder(self.tableSetups, self.buttonSetup)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        item = self.tableLogbook.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id", None))
        item = self.tableLogbook.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date", None))
        item = self.tableLogbook.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "User", None))
        item = self.tableLogbook.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Entry", None))
        item = self.tableLogbook.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "File", None))
        item = self.tableLogbook.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Setup", None))
        item = self.tableLogbook.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Detectors", None))
        item = self.tableLogbook.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Variables", None))
        item = self.tableLogbook.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Comments", None))
        self.buttonLogbook.setText(_translate("MainWindow", "Add entry", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.logbook), _translate("MainWindow", "Logbook", None))
        item = self.tableUsers.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id", None))
        item = self.tableUsers.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.tableUsers.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date", None))
        self.buttonUser.setText(_translate("MainWindow", "Add user", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.users), _translate("MainWindow", "Users", None))
        item = self.tableSetups.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id", None))
        item = self.tableSetups.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column", None))
        item = self.tableSetups.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.tableSetups.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Date", None))
        item = self.tableSetups.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Description", None))
        self.buttonSetup.setText(_translate("MainWindow", "Add setup", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.setups), _translate("MainWindow", "Setups", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.action_Open.setText(_translate("MainWindow", "&Open", None))
        self.action_Quit.setText(_translate("MainWindow", "&Quit", None))
        self.action_New.setText(_translate("MainWindow", "&New", None))

